<a href="https://colab.research.google.com/github/musowjanya/Natural-Language-Processing/blob/main/CasualMask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [ ]:
def causal_mask(seq_len):
    return torch.tril(torch.ones((seq_len, seq_len))).bool()

In [ ]:
causal_mask(4)

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [ ]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [ ]:
# scores = scores.masked_fill(causal_mask == 0, float('-inf'))

In [ ]:
Q = torch.randn(1, 4, 8)  # (batch=1, seq_len=4, d_k=8)
K = torch.randn(1, 4, 8)

In [ ]:
K.shape

torch.Size([1, 4, 8])

In [ ]:
K.transpose(-2, -1).shape

torch.Size([1, 8, 4])

In [ ]:
scores = Q @ K.transpose(-2, -1)

In [ ]:
scores

tensor([[[-1.2046, -0.6229,  5.4357,  2.6786],
         [ 1.1844, -0.4946,  4.8582,  0.6004],
         [ 2.8628,  0.4225,  3.0900,  3.6532],
         [ 0.7793, -0.8210,  2.8679, -4.4831]]])

In [ ]:
scores.shape

torch.Size([1, 4, 4])

In [ ]:
mask = torch.tril(torch.ones(4, 4))

In [ ]:
mask

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [ ]:
scores = scores.masked_fill(mask == 0, float('-inf'))

In [ ]:
scores

tensor([[[-1.2046,    -inf,    -inf,    -inf],
         [ 1.1844, -0.4946,    -inf,    -inf],
         [ 2.8628,  0.4225,  3.0900,    -inf],
         [ 0.7793, -0.8210,  2.8679, -4.4831]]])

In [ ]:
attn = torch.softmax(scores, dim=-1)

In [ ]:
attn

tensor([[[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [8.4277e-01, 1.5723e-01, 0.0000e+00, 0.0000e+00],
         [4.2696e-01, 3.7199e-02, 5.3584e-01, 0.0000e+00],
         [1.0775e-01, 2.1747e-02, 8.6995e-01, 5.5847e-04]]])

In [ ]:
import torch

In [ ]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
mask = torch.full((3,3), float('-inf'))

In [ ]:
mask

tensor([[-inf, -inf, -inf],
        [-inf, -inf, -inf],
        [-inf, -inf, -inf]])

In [ ]:
torch.tril(A)

tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])

In [ ]:
torch.tril(A, diagonal=-1)

tensor([[0, 0, 0],
        [4, 0, 0],
        [7, 8, 0]])

In [ ]:
torch.triu(A)

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])

In [ ]:
torch.triu(A, diagonal=-1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 8, 9]])